id: koeln-gpc
default_language: de
supported_languages: [en]
site_url: https://koeln-gpc.paths.staging.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: f5c57165bb8a2d94c9598c1841c63e072a8c6be7
  dvc_remote: kausal-s3
name: Demonstration BASIC+ Greenhouse Gas Inventory
owner: Köln Stadt
theme_identifier: de-koeln
target_year: 2030
model_end_year: 2045
minimum_historical_year: 2008
maximum_historical_year: 2020
emission_unit: t/a
emission_forecast_from: 2021
emission_dimensions: [scope]
features:
  baseline_visible_in_graphs: true

params:
- id: municipality_name
  value: koeln

dimensions:
- id: energietrager
  label: Energieträger
  categories:
  - id: erdgas
    label: Erdgas
  - id: fern_und_nahwarme
    label: Fern- und Nahwärme
  - id: heizol
    label: Heizöl
  - id: kerosin
    label: Kerosin
  - id: kohle
    label: Kohle
  - id: kraftstoffe
    label: Kraftstoffe
  - id: nicht_definiert
    label: Nicht definiert
  - id: sonstiges
    label: Sonstiges
  - id: strom
    label: Strom

- id: eigentum
  label: Eigentum
  categories:
  - id: gemeinde
    label: Gemeinde
  - id: privat
    label: Privat

- id: scope
  label: Scope
  categories:
  - id: scope1
    label: Scope 1
  - id: scope2
    label: Scope 2

emission_sectors:
- id: net_emissions
  name: Netto Emissionen
  is_outcome: true

nodes:
- id: private_houses_emissions
  name: Private Haushalte
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  color: '#00A969'
  input_dimensions: [energietrager, eigentum, scope]
  output_dimensions: [energietrager, eigentum, scope]
  input_datasets:
  - id: gpc/koeln
    forecast_from: 2021
    filters:
    - column: Sector name
      value: Private Haushalte
  params:
    gpc_sector: I.1
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: energietrager
      flatten: true
    - id: eigentum
      flatten: true

- id: commercial_services_emissions
  name: Gewerbe + Sonstiges
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  color: '#9D0000'
  input_dimensions: [energietrager, eigentum, scope]
  output_dimensions: [energietrager, eigentum, scope]
  input_datasets:
  - id: gpc/koeln
    forecast_from: 2021
    filters:
    - column: Sector name
      value: Gewerbe+ Sonstiges
  params:
    gpc_sector: I.2
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: energietrager
      flatten: true
    - id: eigentum
      flatten: true

- id: industrial_emissions
  name: Gewerbe + Sonstiges
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  color: '#005B99'
  input_dimensions: [energietrager, scope]
  output_dimensions: [energietrager, scope]
  input_datasets:
  - id: gpc/koeln
    forecast_from: 2021
    filters:
    - column: Sector name
      value: Industrie
  params:
    gpc_sector: I.3
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: energietrager
      flatten: true

- id: city_building_emissions
  name: Städtische Gebäude
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  color: '#29ab87'
  input_dimensions: [energietrager, eigentum, scope]
  output_dimensions: [energietrager, eigentum, scope]
  input_datasets:
  - id: gpc/koeln
    forecast_from: 2021
    filters:
    - column: Sector name
      value: Städtische Gebäude
  params:
    gpc_sector: I.2
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: energietrager
      flatten: true
    - id: eigentum
      flatten: true

- id: transport_emissions
  name: Verkehr
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  color: '#AD8F00'
  input_dimensions: [energietrager, scope]
  output_dimensions: [energietrager, scope]
  input_datasets:
  - id: gpc/koeln
    forecast_from: 2021
    filters:
    - column: Sector name
      value: Verkehr
  params:
    gpc_sector: II.1
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: energietrager
      flatten: true

pages:
- id: home
  name: Koeln BASIC+ Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Übersicht Bilanzen Köln
  lead_paragraph: GPC BASIC+ greenhouse gas inventory (2008-2020) and forecast (2021-2020)
    for the City of Koeln.

scenarios:
- id: baseline
  name: Business as Usual

- id: default
  default: true
  name: Climate Action Plan
  all_actions_enabled: true
