id: nzc
default_language: en
supported_languages: [fi]
frameworks: [transport_nzc, buildings_nzc, other_nzc]
site_url: https://nzc.paths.staging.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 6103053c1b69017edc5098e03f1c09f4486f8d5b
  dvc_remote: kausal-s3
name: Demonstration BASIC+ Greenhouse Gas Inventory
owner: City of Demonstration
theme_identifier: default
target_year: 2030
model_end_year: 2045
minimum_historical_year: 2020
maximum_historical_year: 2022
emission_unit: kt/a
emission_forecast_from: 2023
emission_dimensions: [scope, ghg]
features:
  baseline_visible_in_graphs: true

params:
- id: municipality_name
  value: example
- id: discount_rate
  label: Discount rate
  value: 3.5
  min_value: 0
  max_value: 5
  unit: '%'
  is_visible: true
  is_customizable: true
- id: population_growth_rate
  label: Population growth rate
  value: 0.2
  min_value: -2.0
  max_value: 2.0
  unit: '%'
  is_visible: true
  is_customizable: true

action_groups:
- id: transport
  name: Transport
  color: '#93c572'
- id: freight
  name: Freight
- id: buildings
  name: Buildings
  color: '#32cd32'
- id: electricity
  name: Electricity
  color: '#29ab87'
- id: waste
  name: Waste
  color: '#50c878'
- id: scope_3
  name: Scope 3
- id: reforestation
  name: Reforestation

dimensions:

- id: pollutant
  label: Pollutant
  label_fi: Saaste
  categories:
  - id: co2
    label: CO2
    label_fi: CO2
  - id: nox
    label: NOx
    label_fi: NOx
  - id: pm25_combustion
    label: PM2.5 combustion
    label_fi: PM2.5-polttoperäinen
  - id: pm25_wear_tear
    label: PM2.5 wear & tear
    label_fi: PM2.5-kuluminen
  - id: pm10_combustion
    label: PM10 combustion
    label_fi: PM10-polttoperäinen
  - id: pm10_wear_tear
    label: PM10 wear & tear
    label_fi: PM10-kuluminen

- id: transport_pollutant
  label: Transport pollutant
  label_fi: Liikennesaaste
  categories:
  - id: co2
    label: CO2
    label_fi: CO2
  - id: nox
    label: NOx
    label_fi: NOx
  - id: pm25
    label: PM2.5
    label_fi: PM2.5
  - id: pm10
    label: PM10
    label_fi: PM10

- id: scope
  label: Scope
  categories:
  - id: scope1
    label: Scope 1
  - id: scope2
    label: Scope 2

- id: cost_type
  label: Cost Type
  categories:
  - id: energy_costs
    label: Energy Costs
  - id: investment_costs
    label: Investment Costs
  - id: capex
    label: CAPEX (capital expenditure)
  - id: opex
    label: OPEX (operational expenditure)
  - id: maintenance_costs
    label: Maintenance Costs
  - id: operation_cost  # FIXME Overlaps with maintenance_costs
    label: Operation Cost
  - id: sales
    label: Sales income
  - id: air_pollution
    label: Air pollution
  - id: noise
    label: Noise
  - id: accidents
    label: Accidents
  - id: health
    label: Health
  - id: co2_cost
    label: CO2 Cost
  - id: aesthetics
    label: Aesthetics and amenity
  - id: shading
    label: Shading
  - id: water_regulation
    label: Water regulation
  - id: forest_management
    label: Forest management

- id: ghg
  label: Greenhouse gas
  categories:
  - id: co2e
    label: CO2e

- id: transport_mode
  label: Transport mode
  categories:
  - id: cars
    label: Cars
    label_fi: Autot
  - id: buses
    label: Buses
    label_fi: Bussit
  - id: trains
    label: Trains
    label_fi: Junat
  - id: public_transport
    label: Public transport
  - id: walking
    label: Walking
    label_fi: Kävely
  - id: cycling
    label: Cycling
    label_fi: Pyöräily
  - id: light_trucks
    label: Light duty trucks <3.5 tonne
  - id: heavy_trucks
    label: Heavy duty trucks >3.5 tonne
  - id: trucks
    label: Trucks
  - id: other_motorized
    label: Other motorized transport

- id: energy_carrier
  label: Energy carrier
  categories:
  - id: petrol_diesel
    label: Petrol and diesel
  - id: electricity
    label: Electricity
  - id: fossil
    label: Fossil (oil, coal, gas) + direct electric
  - id: heat_pump
    label: Electric heat pumps / geothermal
  - id: bioenergy
    label: Bio (biogas, biomass) and solar heaters
  - id: waste
    label: Waste (fossil & non-fossil waste)

- id: fuel_type
  label: Fuel type
  categories:
  - id: fossil
    label: Fossil
  - id: non_fossil
    label: Non-fossil
  - id: other
    label: Other (e.g. nuclear)
  - id: local_pv
    label: Local photovoltaics
  - id: centralised_pv
    label: Centralised photovoltaics
  - id: pv
    label: Photovoltaics
  - id: flexibility
    label: Flexibility

- id: waste_type
  label: Waste type
  categories:
  - id: paper
    label: Paper and cardboard
  - id: metal
    label: Metal
  - id: plastics
    label: Plastics
  - id: glass
    label: Glass
  - id: organic_waste
    label: Organic waste
  - id: other_waste
    label: Other waste (e.g. textiles, rubble, wood)
  - id: mixed_waste
    label: Mixed waste
  - id: aluminium
    label: Aluminiium

- id: waste_treatment
  label: Waste treatment
  categories:
  - id: other
    label: Other waste management
  - id: incinerated
    label: Incinerated (e.g. energy recovery)
  - id: recycled
    label: Recycled
  - id: decay
    label: Organic decay (waste)
  - id: sorting
    label: Sorting
  - id: plastic_sorting
    label: Plastic sorting
  - id: landfill
    label: Landfill
  - id: landfill_gas
    label: Landfill gas
  - id: composting
    label: Composting

- id: building_energy_class
  label: Building energy class
  categories:
  - id: new_standard
    label: New, standard
  - id: new_top_performance
    label: New, top performance
  - id: old_no_renovations
    label: Old, no renovation
  - id: minor_renovation
    label: Old, minor heating renovation
  - id: major_renovation
    label: Old, extensive heating renovation
  - id: no_improvement  # FIXME Remove redundant
    label: No improvement
  - id: minor_improvements
    label: Minor improvements
  - id: aggressive_improvements
    label: Aggressive improvements
  - id: moderate_improvements
    label: Moderate improvements
  - id: nzeb
    label: Net zero emission buildings

- id: efficiency_programme
  label: Energy efficiency programme
  categories:
  - id: no_improvement
    label: No improvement
  - id: minor_improvements
    label: Minor improvements
  - id: aggressive_improvements
    label: Aggressive improvements
  - id: moderate_improvements
    label: Moderate improvements
  - id: nzeb
    label: Net zero emission buildings

- id: heating_type
  label: Heating type
  categories:
  - id: district_heating
    label: District heating
  - id: local_heating
    label: Local heating

- id: city_area
  label: City area
  categories:
  - id: grey
    label: Grey area
  - id: green
    label: Green area
  - id: grey_inside
    label: Grey area inside city
  - id: green_inside
    label: Green area inside city
  - id: green_outside
    label: Green area outside city
  - id: grey_outside
    label: Grey area outside city

- id: area_distance
  label: Area distance
  categories:
  - id: inside
    label: Inside city
  - id: outside
    label: Outside city

- id: diet
  label: Diet
  categories:
  - id: current_average
    label: Current average
  - id: flexitarian
    label: Flexitarian
  - id: pescetarian
    label: Pescetarian
  - id: vegetarian
    label: Vegetarian
  - id: vegan
    label: Vegan

- id: material
  label: Material
  categories:
  - id: concrete
    label: Concrete
  - id: steel
    label: Steel
  - id: plastics
    label: Plastics
  - id: aluminium
    label: Aluminium

- id: stakeholder
  label: Stakeholder
  categories:
  - id: citizens
    label: Citizens
  - id: property_owners
    label: Property owners
  - id: cities
    label: Cities
  - id: city
    label: City
  - id: healthcare_providers
    label: Healthcare providers
  - id: transport_operators
    label: Transport operators
  - id: utilities
    label: Utilities

emission_sectors:
- id: net_emissions
  name: Net emissions
  is_outcome: true

nodes:
- id: population
  name: Population
  type: costs.ExponentialNode
  quantity: population
  unit: cap
  historical_values: [[2020, 820000]]
  params:
  - id: annual_change
    ref: population_growth_rate

- id: total_electricity_consumption
  name: Total electricity consumption
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  input_dimensions: [energy_carrier]
  output_dimensions: [energy_carrier]

- id: statistical_electricity_consumption
  name: Statistical electricity consumption
  type: simple.AdditiveNode  # FIXME gpc.DatasetNode
  quantity: energy
  unit: GWh/a
  historical_values: [[2018, 2152.0]]
  input_dataset_processors: [LinearInterpolation]
  # input_dimensions: [energy_carrier]
  # output_dimensions: [energy_carrier]
  # input_datasets: [nzc/defaults]
  # params:
  #   sector: Total electricity demand within city boundaries

- id: statistical_electricity_consumption2
  name: Statistical electricity consumption
  description: Total consumption based on population growth. FIXME this causes double
    counting.
  type: simple.MultiplicativeNode
  quantity: energy
  unit: GWh/a
  # input_dimensions: [energy_carrier]
  # output_dimensions: [energy_carrier]
  input_nodes:
  - id: statistical_electricity_consumption
    tags: [non_additive]
  - id: population
    tags: [ratio_to_last_historical_value]
  output_nodes:
  - id: total_electricity_consumption
    to_dimensions:  # FIXME
    - id: energy_carrier
      categories: [electricity]

- id: electricity_production_emission_factor
  name: Electricity production emission factor
  description: TODO Update calculations
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: g/kWh
  input_dimensions: [pollutant, energy_carrier]
  output_dimensions: [pollutant, energy_carrier]
  input_datasets: [nzc/defaults]
  params:
    gpc_sector: electricity production emission factor

- id: co2_unit_price
  name: CO2 unit price
  description: See transport_air_pollution_unit_price.
  type: simple.AdditiveNode
  quantity: unit_price
  unit: EUR/t
  historical_values: [[2010, 100], [2022, 100]]
  input_dataset_processors: [LinearInterpolation]

- id: total_cost
  name: Total cost
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [stakeholder, cost_type]
  output_dimensions: [stakeholder, cost_type]

- id: discounted_total_cost
  name: Discounted total cost
  type: costs.ExponentialNode
  quantity: currency
  unit: MEUR/a
  is_outcome: true
  input_dimensions: [stakeholder, cost_type]
  output_dimensions: [stakeholder, cost_type]
  input_nodes: [total_cost]
  params:
  - id: annual_change
    ref: discount_rate
  - id: is_decreasing_rate
    value: true

actions:
- id: test
  name: Test
  type: simple.AdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2023, 100]]

pages:
- id: home
  name: Demonstration BASIC+ Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Climate Budgeting Tool
  lead_paragraph: Climate budgeting is about including climate emissions systematically
    in the city's planning and budgeting. In the first phase, the Global Protocol
    for Community-Scale (GPC) BASIC-level emissions are considered, and actions reducing
    these emissions are considered. C40 Network's website describes <a 
    href="https://www.c40knowledgehub.org/s/article/Climate-budgets-why-your-city-needs-one?language=en_US">why
    this work is critically important</a>. Oslo has been a <a href="https://www.klimaoslo.no/collection/oslos-climate-budget-2023/">pioneer
    city</a> in this area. They have also made a practical <a 
    href="https://www.c40knowledgehub.org/s/article/Manual-for-climate-budgets-as-a-governance-tool?language=en_US">manual
    for cities</a> to guide through the climate budgeting process.

scenarios:
- id: baseline
  name: Business as Usual

- id: default
  default: true
  name: Climate Action Plan
  all_actions_enabled: true
